'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '../components/header/header';
import Aside from '../components/aside/aside';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function TasksLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <Header />
        <main className='flex'>
          <Aside />
          {children}
        </main>
      </body>
    </html>
  );
}
